name: Update README Stats

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # This allows manual triggering
  # schedule:
  #   - cron: '0 0 */2 * *'  # every 2 days, for example

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Report Script and Update README
        run: python report.py

      - name: Commit and Push Report
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN_ACTION_ACCESS }}
        run: |
          git config --local user.name "don-tpanic"
          git config --local user.email "ken.xiaoliang@gmail.com"
          git add README.md
          git commit -m "Update stats in README [skip ci]" || echo "No changes to commit"
          # Set up remote with PAT authentication
          git remote set-url origin https://don-tpanic:${PAT_TOKEN}@github.com/don-tpanic/alt-core-playground.git
          git push
