name: Update README Stats

on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '0 0 */2 * *'  # every 2 days, for example

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Report Script and Update README
        run: python report.py

      - name: Commit and Push changes
        run: |
          git add README.md
          git commit -m "Update stats in README [skip ci]" || echo "No changes to commit"
          git push
