name: Smoke Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run generator smoke test
        env:
          AZURE_API_VERSION: ${{ secrets.AZURE_API_VERSION }}
          AZURE_API_BASE: ${{ secrets.AZURE_API_BASE }}
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
        run: |
          python -m generators.main --doi 10.1016:j.cognition.2020.104244 --gen-uid ken_c137 --algo-name algo1 --llm azure/gpt-4o-2024-08-06

          # Validate the output using jq
          TOTAL=$(jq '.num_graph_permutations.total' papers/10.1016:j.cognition.2020.104244/gen_ken_c137_algo1_openai-gpt-4o-2024-08-06.json)
          if [ "$TOTAL" -le 3 ]; then
            echo "Error: Total permutations ($TOTAL) must be greater than 3"
            exit 1
          fi
